In [2]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy

In [3]:
iris = datasets.load_iris()

In [9]:
r = skfuzzy.cmeans(data = iris.data.T, c=3, m=2, error=0.005,
                  maxiter=1000, init = None)
r

(array([[5.88841699, 2.7608836 , 4.36319874, 1.39692706],
        [5.00396475, 3.41411435, 1.48277401, 0.25352769],
        [6.77438844, 3.05220084, 5.64600527, 2.05324664]]),
 array([[2.30444063e-03, 1.66596762e-02, 1.37661398e-02, 2.24785325e-02,
         3.76207547e-03, 4.48274657e-02, 1.40106864e-02, 3.11716019e-04,
         4.77435796e-02, 1.19431355e-02, 2.17661036e-02, 5.43554149e-03,
         2.01942356e-02, 5.18172112e-02, 7.26327710e-02, 1.04381210e-01,
         3.55920671e-02, 2.28885402e-03, 6.55864347e-02, 1.41628880e-02,
         2.18691226e-02, 1.03778328e-02, 2.75182693e-02, 1.44732884e-02,
         2.32596543e-02, 1.84719873e-02, 3.58488976e-03, 4.56702572e-03,
         4.32965129e-03, 1.42108118e-02, 1.48094017e-02, 1.77062484e-02,
         4.11599666e-02, 6.35026124e-02, 1.03478705e-02, 1.02052662e-02,
         2.42612488e-02, 6.18380669e-03, 4.11041477e-02, 1.17839298e-03,
         3.58425862e-03, 1.02321547e-01, 3.21917721e-02, 1.43922602e-02,
         3.81504445e-

In [12]:
prev_porcetagem = r[1]
prev_porcetagem[0][0]

0.0023044406336825097

In [13]:
prev_porcetagem[1][0]

0.99662363329815

In [14]:
prev_porcetagem[2][0]

0.0010719260681675486

In [15]:
previsoes = prev_porcetagem.argmax(axis=0)
previsoes

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 0, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0])

In [17]:
resultado = confusion_matrix(iris.target, previsoes)
resultado

array([[ 0, 50,  0],
       [47,  0,  3],
       [13,  0, 37]])