In [16]:
import numpy as np

In [17]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.shape

(3, 5)

In [19]:
a.ndim

2

In [20]:
a.dtype.name

'int64'

In [21]:
a.itemsize

8

In [22]:
a.size

15

In [23]:
type(a)

numpy.ndarray

In [24]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [25]:
type(b)

numpy.ndarray

## Criação de Array

In [26]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [27]:
a.dtype

dtype('int64')

In [28]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [29]:
b.dtype

dtype('float64')

In [30]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [31]:
c = np.array([ [1,2], [3,4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [32]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [34]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [36]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [37]:
from numpy import pi

In [38]:
np.linspace(0 , 2 , 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

## Impressão de Matrizes

In [39]:
a = np.arange(6) # 1d
print(a)

[0 1 2 3 4 5]


In [40]:
b = np.arange(12).reshape(4,3) #2d
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [41]:
c = np.arange(24).reshape(2, 3, 4) #3d
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [42]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [43]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Operações Básicas

In [44]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [45]:
c = a - b
c 

array([20, 29, 38, 47])

In [46]:
b**2

array([0, 1, 4, 9])

In [47]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [48]:
a < 35

array([ True,  True, False, False])

In [49]:
A = np.array([[1,1],
              [0,1]])
B = np.array([[2,0],
              [3,4]])
A * B

array([[2, 0],
       [0, 4]])

In [50]:
A @ B

array([[5, 4],
       [3, 4]])

In [51]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [52]:
rg = np.random.default_rng(1)
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [53]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [54]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [55]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi, 3)
b.dtype.name

'float64'

In [56]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [57]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [58]:
d.dtype.name

'complex128'

In [59]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [60]:
a.sum()

3.1057109529998157

In [61]:
a.min()

0.027559113243068367

In [62]:
a.max()

0.8277025938204418

In [63]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b.sum(axis=0)

array([12, 15, 18, 21])

In [65]:
b.min(axis=1)

array([0, 4, 8])

In [66]:
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Funções Universais

In [67]:
B = np.arange(3)
B

array([0, 1, 2])

In [68]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [69]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [70]:
C = np.array([2., -1., 4.])

In [71]:
np.add(B, C)

array([2., 0., 6.])

## Indexação, divisão e iteração

In [72]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [73]:
a[2]

8

In [74]:
a[2:5]

array([ 8, 27, 64])

In [75]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [76]:
a[ : :-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [77]:
for i in a:
    print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [78]:
def f(x, y):
    return 10*x+y


In [79]:
b = np.fromfunction(f,(5,4), dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [80]:
b[2,3]

23

In [81]:
b[0:5, 1]

array([ 1, 11, 21, 31, 41])

In [82]:
b[: ,1]

array([ 1, 11, 21, 31, 41])

In [83]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [84]:
b[-1]

array([40, 41, 42, 43])

In [85]:
c = np.array( [[[ 0, 1, 2,],
                [10, 12, 13]],
               [[100, 101, 102],
                [110, 112, 113]]])

In [86]:
c.shape

(2, 2, 3)

In [87]:
c[1,...]

array([[100, 101, 102],
       [110, 112, 113]])

In [88]:
c[...,2]

array([[  2,  13],
       [102, 113]])

In [89]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [90]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


## Manipulação de Forma

### Alterar a forma de um array

In [91]:
a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [92]:
a.shape

(3, 4)

In [93]:
a.ravel()

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [94]:
a.reshape(2,6)

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [95]:
a.T.shape

(4, 3)

In [96]:
a.shape

(3, 4)

In [97]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [98]:
a.resize((2,6))

In [99]:
a.reshape(3, -1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

## Empilhar diferentes matrizes

In [100]:
a = np.floor(10*rg.random((2,2)))
a

array([[9., 7.],
       [5., 2.]])

In [101]:
b = np.floor(10*rg.random((2,2)))
b

array([[1., 9.],
       [5., 1.]])

In [102]:
np.vstack((a,b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [103]:
np.hstack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [104]:
from numpy import newaxis

In [105]:
np.column_stack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [106]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a,b))

array([[4., 3.],
       [2., 8.]])

In [107]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [108]:
a[:, newaxis]

array([[4.],
       [2.]])

In [109]:
np.column_stack((a[:,newaxis], b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [110]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [111]:
np.column_stack is np.hstack

False

In [112]:
np.row_stack is np.vstack

True

In [113]:
np.r_[1:4, 0, 4]

array([1, 2, 3, 0, 4])

## Dividindo uma matriz em várias outras menores

In [114]:
a = np.floor(10*rg.random((2,12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [115]:
np.hsplit(a, 3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]), array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]), array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [116]:
np.hsplit(a,(3,4))

[array([[6., 7., 6.],
        [8., 5., 5.]]), array([[9.],
        [7.]]), array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

## Cópias e visualizações

### Nenhuma cópia

In [118]:
a = np.array([[ 0, 1, 2, 3],
              [ 4, 5, 6, 7],
              [ 8, 9, 10,11]])
b = a
b is a

True

In [119]:
def f(x):
    print(id(x))

In [120]:
id(a)

139923797974192

In [121]:
f(a)

139923797974192


## Exibir ou cópia superficial

In [122]:
c = a.view()
c is a

False

In [123]:
c.base is a

True

In [124]:
c.flags.owndata

False

In [125]:
c = c.reshape((2, 6))

In [126]:
a.shape

(3, 4)

In [127]:
c[0, 4] = 1234

In [128]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [129]:
s = a[ : , 1:3]

In [130]:
s[:] = 10

In [131]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

## Deep Copy

In [132]:
d = a.copy()
d is a

False

In [133]:
d.base is a

False

In [134]:
d[0, 0] = 9999

In [135]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

In [136]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a

## Indexando com Matrizes de Índices

In [137]:
a = np.arange(12)**2
i = np.array([1, 1, 3, 8, 5])
a[i]

array([ 1,  1,  9, 64, 25])

In [138]:
j = np.array([[3, 4], [9, 7]])
a[j]

array([[ 9, 16],
       [81, 49]])

In [144]:
palette = np.array([[0, 0, 0],
                    [255, 0, 0],
                    [0, 255, 0],
                    [0, 0, 255],
                    [255, 255, 255]])
image = np.array([[0, 1, 2, 0],
                  [0, 3, 4, 0]])

In [145]:
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [146]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
i = np.array([[0, 1],
              [1, 2]])

In [148]:
j = np.array([[2, 1],
              [3, 3]])

In [149]:
a[i, j]

array([[ 2,  5],
       [ 7, 11]])

In [150]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [151]:
a[:, j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [152]:
l =(i, j)

In [153]:
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [157]:
s = np.array([i, j])
a[s]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [158]:
a[tuple(s)]

array([[ 2,  5],
       [ 7, 11]])

In [159]:
time = np.linspace(20, 145, 5)
data = np.sin(np.arange(20)).reshape(5,4)

In [160]:
time

array([ 20.  ,  51.25,  82.5 , 113.75, 145.  ])

In [161]:
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [162]:
ind = data.argmax(axis=0)
ind

array([2, 0, 3, 1])

In [163]:
time_max = time[ind]
time_max

array([ 82.5 ,  20.  , 113.75,  51.25])

In [164]:
data_max = data[ind, range(data.shape[1])]
data_max

array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [165]:
np.all(data_max == data.max(axis=0))

True

In [166]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [167]:
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [168]:
a = np.arange(5)
a[[0, 0, 2]] = [1,2,3]
a

array([2, 1, 3, 3, 4])

## Algebra Linear

### Operações de array simples

In [169]:
a = np.array([[1.0, 2.0], [3.0, 4.0]])
print(a)

[[1. 2.]
 [3. 4.]]


In [170]:
a.transpose()

array([[1., 3.],
       [2., 4.]])

In [171]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [172]:
u = np.eye(2)
u

array([[1., 0.],
       [0., 1.]])

In [173]:
j = np.array([[0.0, -1.0], [1.0, 0.0]])

In [174]:
j @ j

array([[-1.,  0.],
       [ 0., -1.]])

In [175]:
np.trace(u)

2.0

In [176]:
y = np.array([[5.], [7.]])

In [177]:
np.linalg.solve(a, y)

array([[-3.],
       [ 4.]])

In [178]:
np.linalg.eig(j)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))