In [25]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from yellowbrick.classifier import ConfusionMatrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np
from sklearn.metrics import confusion_matrix

In [26]:
data = datasets.load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [27]:
previsores = data.data
classe = data.target

In [28]:
classe_dummy = np_utils.to_categorical(classe)
print(classe_dummy)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [29]:
X_treino, X_teste, y_treino, y_teste = train_test_split(previsores,
                                                       classe_dummy,
                                                       test_size = 0.3,
                                                       random_state = 0)

In [30]:
modelo = Sequential()
modelo.add(Dense(units=5, input_dim=4))
modelo.add(Dense(units=4))
modelo.add(Dense(units=3, activation='softmax'))

In [31]:
modelo.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_7 (Dense)              (None, 5)                 25        
_________________________________________________________________
dense_8 (Dense)              (None, 4)                 24        
_________________________________________________________________
dense_9 (Dense)              (None, 3)                 15        
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [32]:
#Impressão
from keras.utils.vis_utils import plot_model


In [33]:
modelo.compile(optimizer='adam', loss='categorical_crossentropy',
              metrics=['accuracy'])
modelo.fit(X_treino, y_treino, epochs=1000,
          validation_data=(X_teste, y_teste))

Train on 105 samples, validate on 45 samples
Epoch 1/1000
105/105 [==============================] - 0s 2ms/step - loss: 2.0957 - accuracy: 0.3714 - val_loss: 2.3541 - val_accuracy: 0.2444
Epoch 2/1000
105/105 [==============================] - 0s 124us/step - loss: 1.9603 - accuracy: 0.3714 - val_loss: 2.1875 - val_accuracy: 0.2444
Epoch 3/1000
105/105 [==============================] - 0s 195us/step - loss: 1.8268 - accuracy: 0.3714 - val_loss: 2.0301 - val_accuracy: 0.2444
Epoch 4/1000
105/105 [==============================] - 0s 172us/step - loss: 1.7127 - accuracy: 0.3714 - val_loss: 1.8823 - val_accuracy: 0.2444
Epoch 5/1000
105/105 [==============================] - 0s 130us/step - loss: 1.5971 - accuracy: 0.3714 - val_loss: 1.7503 - val_accuracy: 0.2444
Epoch 6/1000
105/105 [==============================] - 0s 210us/step - loss: 1.4969 - accuracy: 0.3714 - val_loss: 1.6283 - val_accuracy: 0.2444
Epoch 7/1000
105/105 [==============================] - 0s 265us/step - loss: 1.4

105/105 [==============================] - 0s 266us/step - loss: 0.5881 - accuracy: 0.6952 - val_loss: 0.6153 - val_accuracy: 0.6000
Epoch 57/1000
105/105 [==============================] - 0s 188us/step - loss: 0.5819 - accuracy: 0.7048 - val_loss: 0.6092 - val_accuracy: 0.6000
Epoch 58/1000
105/105 [==============================] - 0s 149us/step - loss: 0.5757 - accuracy: 0.7048 - val_loss: 0.6066 - val_accuracy: 0.6000
Epoch 59/1000
105/105 [==============================] - 0s 162us/step - loss: 0.5702 - accuracy: 0.6952 - val_loss: 0.6028 - val_accuracy: 0.6000
Epoch 60/1000
105/105 [==============================] - 0s 172us/step - loss: 0.5646 - accuracy: 0.6952 - val_loss: 0.5975 - val_accuracy: 0.6000
Epoch 61/1000
105/105 [==============================] - 0s 188us/step - loss: 0.5591 - accuracy: 0.6952 - val_loss: 0.5919 - val_accuracy: 0.6000
Epoch 62/1000
105/105 [==============================] - 0s 169us/step - loss: 0.5538 - accuracy: 0.6952 - val_loss: 0.5875 - val_ac

Epoch 112/1000
105/105 [==============================] - 0s 114us/step - loss: 0.3648 - accuracy: 0.9524 - val_loss: 0.3777 - val_accuracy: 0.9778
Epoch 113/1000
105/105 [==============================] - 0s 165us/step - loss: 0.3622 - accuracy: 0.9619 - val_loss: 0.3742 - val_accuracy: 0.9778
Epoch 114/1000
105/105 [==============================] - 0s 215us/step - loss: 0.3586 - accuracy: 0.9619 - val_loss: 0.3731 - val_accuracy: 0.9778
Epoch 115/1000
105/105 [==============================] - 0s 171us/step - loss: 0.3546 - accuracy: 0.9524 - val_loss: 0.3743 - val_accuracy: 0.9333
Epoch 116/1000
105/105 [==============================] - 0s 211us/step - loss: 0.3512 - accuracy: 0.9429 - val_loss: 0.3765 - val_accuracy: 0.9333
Epoch 117/1000
105/105 [==============================] - 0s 201us/step - loss: 0.3484 - accuracy: 0.9429 - val_loss: 0.3775 - val_accuracy: 0.9333
Epoch 118/1000
105/105 [==============================] - 0s 167us/step - loss: 0.3450 - accuracy: 0.9429 - val_

105/105 [==============================] - 0s 148us/step - loss: 0.2234 - accuracy: 0.9619 - val_loss: 0.2476 - val_accuracy: 0.9778
Epoch 168/1000
105/105 [==============================] - 0s 246us/step - loss: 0.2213 - accuracy: 0.9619 - val_loss: 0.2469 - val_accuracy: 0.9778
Epoch 169/1000
105/105 [==============================] - 0s 194us/step - loss: 0.2192 - accuracy: 0.9619 - val_loss: 0.2485 - val_accuracy: 0.9778
Epoch 170/1000
105/105 [==============================] - 0s 213us/step - loss: 0.2177 - accuracy: 0.9619 - val_loss: 0.2493 - val_accuracy: 0.9778
Epoch 171/1000
105/105 [==============================] - 0s 178us/step - loss: 0.2160 - accuracy: 0.9619 - val_loss: 0.2471 - val_accuracy: 0.9778
Epoch 172/1000
105/105 [==============================] - 0s 192us/step - loss: 0.2141 - accuracy: 0.9619 - val_loss: 0.2434 - val_accuracy: 0.9778
Epoch 173/1000
105/105 [==============================] - 0s 140us/step - loss: 0.2121 - accuracy: 0.9619 - val_loss: 0.2371 - 

105/105 [==============================] - 0s 151us/step - loss: 0.1463 - accuracy: 0.9714 - val_loss: 0.1660 - val_accuracy: 0.9778
Epoch 223/1000
105/105 [==============================] - 0s 199us/step - loss: 0.1456 - accuracy: 0.9714 - val_loss: 0.1650 - val_accuracy: 0.9778
Epoch 224/1000
105/105 [==============================] - 0s 207us/step - loss: 0.1447 - accuracy: 0.9714 - val_loss: 0.1605 - val_accuracy: 0.9778
Epoch 225/1000
105/105 [==============================] - 0s 268us/step - loss: 0.1442 - accuracy: 0.9619 - val_loss: 0.1589 - val_accuracy: 0.9778
Epoch 226/1000
105/105 [==============================] - 0s 213us/step - loss: 0.1436 - accuracy: 0.9714 - val_loss: 0.1581 - val_accuracy: 0.9778
Epoch 227/1000
105/105 [==============================] - 0s 188us/step - loss: 0.1424 - accuracy: 0.9619 - val_loss: 0.1604 - val_accuracy: 0.9778
Epoch 228/1000
105/105 [==============================] - 0s 211us/step - loss: 0.1415 - accuracy: 0.9714 - val_loss: 0.1611 - 

105/105 [==============================] - 0s 182us/step - loss: 0.1093 - accuracy: 0.9714 - val_loss: 0.1313 - val_accuracy: 0.9778
Epoch 278/1000
105/105 [==============================] - 0s 188us/step - loss: 0.1100 - accuracy: 0.9714 - val_loss: 0.1337 - val_accuracy: 0.9778
Epoch 279/1000
105/105 [==============================] - 0s 162us/step - loss: 0.1091 - accuracy: 0.9714 - val_loss: 0.1317 - val_accuracy: 0.9778
Epoch 280/1000
105/105 [==============================] - 0s 231us/step - loss: 0.1084 - accuracy: 0.9714 - val_loss: 0.1290 - val_accuracy: 0.9778
Epoch 281/1000
105/105 [==============================] - 0s 161us/step - loss: 0.1079 - accuracy: 0.9714 - val_loss: 0.1292 - val_accuracy: 0.9778
Epoch 282/1000
105/105 [==============================] - 0s 273us/step - loss: 0.1081 - accuracy: 0.9714 - val_loss: 0.1305 - val_accuracy: 0.9778
Epoch 283/1000
105/105 [==============================] - 0s 172us/step - loss: 0.1078 - accuracy: 0.9714 - val_loss: 0.1271 - 

105/105 [==============================] - 0s 189us/step - loss: 0.0902 - accuracy: 0.9619 - val_loss: 0.1079 - val_accuracy: 0.9778
Epoch 333/1000
105/105 [==============================] - 0s 210us/step - loss: 0.0895 - accuracy: 0.9714 - val_loss: 0.1095 - val_accuracy: 0.9778
Epoch 334/1000
105/105 [==============================] - 0s 202us/step - loss: 0.0899 - accuracy: 0.9714 - val_loss: 0.1111 - val_accuracy: 0.9778
Epoch 335/1000
105/105 [==============================] - 0s 144us/step - loss: 0.0895 - accuracy: 0.9714 - val_loss: 0.1119 - val_accuracy: 0.9778
Epoch 336/1000
105/105 [==============================] - 0s 206us/step - loss: 0.0898 - accuracy: 0.9714 - val_loss: 0.1112 - val_accuracy: 0.9778
Epoch 337/1000
105/105 [==============================] - 0s 151us/step - loss: 0.0895 - accuracy: 0.9714 - val_loss: 0.1076 - val_accuracy: 0.9778
Epoch 338/1000
105/105 [==============================] - 0s 172us/step - loss: 0.0884 - accuracy: 0.9714 - val_loss: 0.1072 - 

105/105 [==============================] - 0s 215us/step - loss: 0.0786 - accuracy: 0.9714 - val_loss: 0.0984 - val_accuracy: 0.9778
Epoch 388/1000
105/105 [==============================] - 0s 197us/step - loss: 0.0787 - accuracy: 0.9714 - val_loss: 0.0983 - val_accuracy: 0.9778
Epoch 389/1000
105/105 [==============================] - 0s 168us/step - loss: 0.0784 - accuracy: 0.9714 - val_loss: 0.0962 - val_accuracy: 0.9778
Epoch 390/1000
105/105 [==============================] - 0s 154us/step - loss: 0.0772 - accuracy: 0.9619 - val_loss: 0.0901 - val_accuracy: 0.9778
Epoch 391/1000
105/105 [==============================] - 0s 227us/step - loss: 0.0800 - accuracy: 0.9619 - val_loss: 0.0871 - val_accuracy: 0.9778
Epoch 392/1000
105/105 [==============================] - 0s 197us/step - loss: 0.0801 - accuracy: 0.9619 - val_loss: 0.0875 - val_accuracy: 0.9778
Epoch 393/1000
105/105 [==============================] - 0s 146us/step - loss: 0.0788 - accuracy: 0.9619 - val_loss: 0.0891 - 

105/105 [==============================] - 0s 229us/step - loss: 0.0718 - accuracy: 0.9619 - val_loss: 0.0837 - val_accuracy: 0.9778
Epoch 443/1000
105/105 [==============================] - 0s 162us/step - loss: 0.0706 - accuracy: 0.9619 - val_loss: 0.0871 - val_accuracy: 0.9778
Epoch 444/1000
105/105 [==============================] - 0s 207us/step - loss: 0.0709 - accuracy: 0.9619 - val_loss: 0.0913 - val_accuracy: 0.9778
Epoch 445/1000
105/105 [==============================] - 0s 180us/step - loss: 0.0710 - accuracy: 0.9714 - val_loss: 0.0927 - val_accuracy: 0.9778
Epoch 446/1000
105/105 [==============================] - 0s 154us/step - loss: 0.0715 - accuracy: 0.9714 - val_loss: 0.0920 - val_accuracy: 0.9778
Epoch 447/1000
105/105 [==============================] - 0s 148us/step - loss: 0.0701 - accuracy: 0.9714 - val_loss: 0.0869 - val_accuracy: 0.9778
Epoch 448/1000
105/105 [==============================] - 0s 232us/step - loss: 0.0702 - accuracy: 0.9619 - val_loss: 0.0820 - 

105/105 [==============================] - 0s 200us/step - loss: 0.0661 - accuracy: 0.9619 - val_loss: 0.0760 - val_accuracy: 0.9778
Epoch 498/1000
105/105 [==============================] - 0s 131us/step - loss: 0.0678 - accuracy: 0.9619 - val_loss: 0.0761 - val_accuracy: 0.9778
Epoch 499/1000
105/105 [==============================] - 0s 284us/step - loss: 0.0668 - accuracy: 0.9524 - val_loss: 0.0776 - val_accuracy: 0.9778
Epoch 500/1000
105/105 [==============================] - 0s 208us/step - loss: 0.0644 - accuracy: 0.9619 - val_loss: 0.0825 - val_accuracy: 0.9778
Epoch 501/1000
105/105 [==============================] - 0s 195us/step - loss: 0.0649 - accuracy: 0.9619 - val_loss: 0.0883 - val_accuracy: 0.9778
Epoch 502/1000
105/105 [==============================] - 0s 197us/step - loss: 0.0665 - accuracy: 0.9714 - val_loss: 0.0926 - val_accuracy: 0.9778
Epoch 503/1000
105/105 [==============================] - 0s 176us/step - loss: 0.0669 - accuracy: 0.9714 - val_loss: 0.0903 - 

105/105 [==============================] - 0s 250us/step - loss: 0.0615 - accuracy: 0.9619 - val_loss: 0.0834 - val_accuracy: 0.9778
Epoch 553/1000
105/105 [==============================] - 0s 197us/step - loss: 0.0613 - accuracy: 0.9619 - val_loss: 0.0802 - val_accuracy: 0.9778
Epoch 554/1000
105/105 [==============================] - 0s 227us/step - loss: 0.0610 - accuracy: 0.9619 - val_loss: 0.0780 - val_accuracy: 0.9778
Epoch 555/1000
105/105 [==============================] - 0s 232us/step - loss: 0.0615 - accuracy: 0.9619 - val_loss: 0.0759 - val_accuracy: 0.9778
Epoch 556/1000
105/105 [==============================] - 0s 195us/step - loss: 0.0611 - accuracy: 0.9619 - val_loss: 0.0759 - val_accuracy: 0.9778
Epoch 557/1000
105/105 [==============================] - 0s 215us/step - loss: 0.0609 - accuracy: 0.9619 - val_loss: 0.0765 - val_accuracy: 0.9778
Epoch 558/1000
105/105 [==============================] - 0s 258us/step - loss: 0.0607 - accuracy: 0.9619 - val_loss: 0.0770 - 

105/105 [==============================] - 0s 229us/step - loss: 0.0581 - accuracy: 0.9619 - val_loss: 0.0770 - val_accuracy: 0.9778
Epoch 608/1000
105/105 [==============================] - 0s 188us/step - loss: 0.0574 - accuracy: 0.9619 - val_loss: 0.0780 - val_accuracy: 0.9778
Epoch 609/1000
105/105 [==============================] - 0s 216us/step - loss: 0.0572 - accuracy: 0.9619 - val_loss: 0.0764 - val_accuracy: 0.9778
Epoch 610/1000
105/105 [==============================] - 0s 178us/step - loss: 0.0591 - accuracy: 0.9619 - val_loss: 0.0739 - val_accuracy: 0.9778
Epoch 611/1000
105/105 [==============================] - 0s 197us/step - loss: 0.0577 - accuracy: 0.9619 - val_loss: 0.0768 - val_accuracy: 0.9778
Epoch 612/1000
105/105 [==============================] - 0s 222us/step - loss: 0.0579 - accuracy: 0.9619 - val_loss: 0.0797 - val_accuracy: 0.9778
Epoch 613/1000
105/105 [==============================] - 0s 241us/step - loss: 0.0573 - accuracy: 0.9619 - val_loss: 0.0805 - 

105/105 [==============================] - 0s 214us/step - loss: 0.0546 - accuracy: 0.9619 - val_loss: 0.0758 - val_accuracy: 0.9778
Epoch 663/1000
105/105 [==============================] - 0s 234us/step - loss: 0.0546 - accuracy: 0.9619 - val_loss: 0.0771 - val_accuracy: 0.9778
Epoch 664/1000
105/105 [==============================] - 0s 202us/step - loss: 0.0545 - accuracy: 0.9619 - val_loss: 0.0781 - val_accuracy: 0.9778
Epoch 665/1000
105/105 [==============================] - 0s 172us/step - loss: 0.0546 - accuracy: 0.9619 - val_loss: 0.0771 - val_accuracy: 0.9778
Epoch 666/1000
105/105 [==============================] - 0s 207us/step - loss: 0.0553 - accuracy: 0.9619 - val_loss: 0.0734 - val_accuracy: 0.9778
Epoch 667/1000
105/105 [==============================] - 0s 159us/step - loss: 0.0547 - accuracy: 0.9714 - val_loss: 0.0735 - val_accuracy: 0.9778
Epoch 668/1000
105/105 [==============================] - 0s 245us/step - loss: 0.0545 - accuracy: 0.9619 - val_loss: 0.0752 - 

105/105 [==============================] - 0s 307us/step - loss: 0.0525 - accuracy: 0.9619 - val_loss: 0.0801 - val_accuracy: 0.9778
Epoch 718/1000
105/105 [==============================] - 0s 267us/step - loss: 0.0525 - accuracy: 0.9619 - val_loss: 0.0787 - val_accuracy: 0.9778
Epoch 719/1000
105/105 [==============================] - 0s 227us/step - loss: 0.0527 - accuracy: 0.9619 - val_loss: 0.0738 - val_accuracy: 0.9778
Epoch 720/1000
105/105 [==============================] - 0s 194us/step - loss: 0.0519 - accuracy: 0.9714 - val_loss: 0.0723 - val_accuracy: 0.9778
Epoch 721/1000
105/105 [==============================] - 0s 222us/step - loss: 0.0538 - accuracy: 0.9810 - val_loss: 0.0704 - val_accuracy: 0.9778
Epoch 722/1000
105/105 [==============================] - 0s 187us/step - loss: 0.0536 - accuracy: 0.9810 - val_loss: 0.0717 - val_accuracy: 0.9778
Epoch 723/1000
105/105 [==============================] - 0s 246us/step - loss: 0.0532 - accuracy: 0.9714 - val_loss: 0.0723 - 

105/105 [==============================] - 0s 269us/step - loss: 0.0519 - accuracy: 0.9810 - val_loss: 0.0710 - val_accuracy: 0.9778
Epoch 773/1000
105/105 [==============================] - 0s 158us/step - loss: 0.0523 - accuracy: 0.9714 - val_loss: 0.0713 - val_accuracy: 0.9778
Epoch 774/1000
105/105 [==============================] - 0s 184us/step - loss: 0.0520 - accuracy: 0.9714 - val_loss: 0.0753 - val_accuracy: 0.9778
Epoch 775/1000
105/105 [==============================] - 0s 163us/step - loss: 0.0497 - accuracy: 0.9714 - val_loss: 0.0760 - val_accuracy: 0.9778
Epoch 776/1000
105/105 [==============================] - 0s 238us/step - loss: 0.0499 - accuracy: 0.9714 - val_loss: 0.0760 - val_accuracy: 0.9778
Epoch 777/1000
105/105 [==============================] - 0s 201us/step - loss: 0.0504 - accuracy: 0.9714 - val_loss: 0.0734 - val_accuracy: 0.9778
Epoch 778/1000
105/105 [==============================] - 0s 178us/step - loss: 0.0500 - accuracy: 0.9714 - val_loss: 0.0737 - 

105/105 [==============================] - 0s 248us/step - loss: 0.0480 - accuracy: 0.9714 - val_loss: 0.0780 - val_accuracy: 0.9778
Epoch 828/1000
105/105 [==============================] - 0s 215us/step - loss: 0.0481 - accuracy: 0.9714 - val_loss: 0.0782 - val_accuracy: 0.9778
Epoch 829/1000
105/105 [==============================] - 0s 142us/step - loss: 0.0481 - accuracy: 0.9714 - val_loss: 0.0773 - val_accuracy: 0.9778
Epoch 830/1000
105/105 [==============================] - 0s 223us/step - loss: 0.0485 - accuracy: 0.9714 - val_loss: 0.0734 - val_accuracy: 0.9778
Epoch 831/1000
105/105 [==============================] - 0s 227us/step - loss: 0.0490 - accuracy: 0.9810 - val_loss: 0.0725 - val_accuracy: 0.9778
Epoch 832/1000
105/105 [==============================] - 0s 171us/step - loss: 0.0489 - accuracy: 0.9714 - val_loss: 0.0746 - val_accuracy: 0.9778
Epoch 833/1000
105/105 [==============================] - 0s 243us/step - loss: 0.0480 - accuracy: 0.9714 - val_loss: 0.0747 - 

105/105 [==============================] - 0s 204us/step - loss: 0.0469 - accuracy: 0.9810 - val_loss: 0.0734 - val_accuracy: 0.9778
Epoch 883/1000
105/105 [==============================] - 0s 207us/step - loss: 0.0472 - accuracy: 0.9810 - val_loss: 0.0727 - val_accuracy: 0.9778
Epoch 884/1000
105/105 [==============================] - 0s 138us/step - loss: 0.0483 - accuracy: 0.9810 - val_loss: 0.0717 - val_accuracy: 0.9778
Epoch 885/1000
105/105 [==============================] - 0s 241us/step - loss: 0.0478 - accuracy: 0.9810 - val_loss: 0.0729 - val_accuracy: 0.9778
Epoch 886/1000
105/105 [==============================] - 0s 176us/step - loss: 0.0475 - accuracy: 0.9810 - val_loss: 0.0744 - val_accuracy: 0.9778
Epoch 887/1000
105/105 [==============================] - 0s 163us/step - loss: 0.0464 - accuracy: 0.9810 - val_loss: 0.0745 - val_accuracy: 0.9778
Epoch 888/1000
105/105 [==============================] - 0s 213us/step - loss: 0.0464 - accuracy: 0.9810 - val_loss: 0.0757 - 

105/105 [==============================] - 0s 230us/step - loss: 0.0447 - accuracy: 0.9714 - val_loss: 0.0781 - val_accuracy: 0.9778
Epoch 938/1000
105/105 [==============================] - 0s 177us/step - loss: 0.0451 - accuracy: 0.9714 - val_loss: 0.0770 - val_accuracy: 0.9778
Epoch 939/1000
105/105 [==============================] - 0s 166us/step - loss: 0.0449 - accuracy: 0.9714 - val_loss: 0.0772 - val_accuracy: 0.9778
Epoch 940/1000
105/105 [==============================] - 0s 196us/step - loss: 0.0448 - accuracy: 0.9714 - val_loss: 0.0747 - val_accuracy: 0.9778
Epoch 941/1000
105/105 [==============================] - 0s 192us/step - loss: 0.0462 - accuracy: 0.9810 - val_loss: 0.0720 - val_accuracy: 0.9778
Epoch 942/1000
105/105 [==============================] - 0s 134us/step - loss: 0.0485 - accuracy: 0.9810 - val_loss: 0.0708 - val_accuracy: 0.9778
Epoch 943/1000
105/105 [==============================] - 0s 186us/step - loss: 0.0479 - accuracy: 0.9810 - val_loss: 0.0719 - 

105/105 [==============================] - 0s 152us/step - loss: 0.0438 - accuracy: 0.9714 - val_loss: 0.0783 - val_accuracy: 0.9778
Epoch 992/1000
105/105 [==============================] - 0s 176us/step - loss: 0.0432 - accuracy: 0.9714 - val_loss: 0.0814 - val_accuracy: 0.9778
Epoch 993/1000
105/105 [==============================] - 0s 148us/step - loss: 0.0436 - accuracy: 0.9714 - val_loss: 0.0823 - val_accuracy: 0.9778
Epoch 994/1000
105/105 [==============================] - 0s 179us/step - loss: 0.0435 - accuracy: 0.9714 - val_loss: 0.0809 - val_accuracy: 0.9778
Epoch 995/1000
105/105 [==============================] - 0s 236us/step - loss: 0.0432 - accuracy: 0.9714 - val_loss: 0.0795 - val_accuracy: 0.9778
Epoch 996/1000
105/105 [==============================] - 0s 164us/step - loss: 0.0430 - accuracy: 0.9714 - val_loss: 0.0790 - val_accuracy: 0.9778
Epoch 997/1000
105/105 [==============================] - 0s 218us/step - loss: 0.0434 - accuracy: 0.9714 - val_loss: 0.0790 - 

In [36]:
previsoes = modelo.predict(X_teste)
print(previsoes)

[[3.9873703e-14 1.4955109e-06 9.9999845e-01]
 [1.3848073e-04 9.9978024e-01 8.1226994e-05]
 [9.9998951e-01 1.0461818e-05 3.3188996e-27]
 [4.8377140e-12 7.9892296e-04 9.9920112e-01]
 [9.9974972e-01 2.5033520e-04 3.0129693e-22]
 [4.0678773e-16 1.4714716e-07 9.9999988e-01]
 [9.9987590e-01 1.2413181e-04 6.4033215e-23]
 [2.2483944e-05 9.9906689e-01 9.1064931e-04]
 [8.8681181e-06 9.9757403e-01 2.4170307e-03]
 [2.8053683e-04 9.9967372e-01 4.5808127e-05]
 [2.0177584e-09 1.3349557e-02 9.8665047e-01]
 [6.4189764e-05 9.9951243e-01 4.2335174e-04]
 [2.5809290e-05 9.9782735e-01 2.1468457e-03]
 [1.1762029e-05 9.9229515e-01 7.6931948e-03]
 [1.4936605e-05 9.8595715e-01 1.4027904e-02]
 [9.9994206e-01 5.7927802e-05 3.9663571e-24]
 [2.0988591e-05 9.8184997e-01 1.8129110e-02]
 [3.7291684e-05 9.8678619e-01 1.3176492e-02]
 [9.9898356e-01 1.0164077e-03 7.1651276e-20]
 [9.9995422e-01 4.5805213e-05 1.0037331e-24]
 [1.3504396e-10 4.2597041e-04 9.9957401e-01]
 [2.5062847e-05 9.4496679e-01 5.5008229e-02]
 [9.986771

In [37]:
previsoes = (previsoes > 0.5)
print(previsoes)

[[False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]]


In [39]:
y_teste_matrix = [np.argmax(t) for t in y_teste]
y_previsao_matrix = [np.argmax(t) for t in previsoes]

In [40]:
confusao = confusion_matrix(y_teste_matrix, y_previsao_matrix)
print(confusao)

[[16  0  0]
 [ 0 17  1]
 [ 0  0 11]]
