In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.svm import SVC

/home/filipanselmo/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/filipanselmo/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
credito = pd.read_csv('Credit.csv')
prev = credito.iloc[:,0:20].values
classe = credito.iloc[:,20].values

In [5]:
labelencoder = LabelEncoder()
prev[:,0] = labelencoder.fit_transform(prev[:,0])
prev[:,2] = labelencoder.fit_transform(prev[:,2])
prev[:,3] = labelencoder.fit_transform(prev[:,3])
prev[:,5] = labelencoder.fit_transform(prev[:,5])
prev[:,6] = labelencoder.fit_transform(prev[:,6])
prev[:,8] = labelencoder.fit_transform(prev[:,8])
prev[:,9] = labelencoder.fit_transform(prev[:,9])
prev[:,11] = labelencoder.fit_transform(prev[:,11])
prev[:,13] = labelencoder.fit_transform(prev[:,13])
prev[:,14] = labelencoder.fit_transform(prev[:,14])
prev[:,16] = labelencoder.fit_transform(prev[:,16])
prev[:,18] = labelencoder.fit_transform(prev[:,18])
prev[:,19] = labelencoder.fit_transform(prev[:,19])

X_treino, X_teste, y_treino, y_teste = train_test_split(prev,
                                                       classe,
                                                       test_size = 0.3,
                                                       random_state = 0)


In [6]:
prev[0]

array([2, 6, 1, 7, 1169, 0, 3, 4, 3, 2, 4, 2, 67, 1, 1, 2, 3, 1, 1, 1],
      dtype=object)

In [10]:
svm = SVC()
svm.fit(X_treino, y_treino)

/home/filipanselmo/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [14]:
y_teste

array(['good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'bad', 'bad', 'good', 'good', 'bad', 'good', 'good',
       'bad', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'bad', 'good', 'good', 'good', 'bad', 'good', 'good', 'bad', 'bad',
       'good', 'bad', 'good', 'good', 'bad', 'good', 'bad', 'good',
       'good', 'good', 'good', 'bad', 'bad', 'good', 'good', 'good',
       'bad', 'bad', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'bad', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'bad', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'good', 'bad', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'bad', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'bad', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'bad', 'bad', 'good', 'good', 'bad', 'bad', 'good', 'good',
       'goo

In [13]:
previsoes = svm.predict(X_teste)
previsoes

array(['good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
      

In [15]:
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.7133333333333334

In [16]:
from sklearn.ensemble import ExtraTreesClassifier

In [17]:
floresta = ExtraTreesClassifier()
floresta.fit(X_treino, y_treino)

/home/filipanselmo/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
                     max_depth=None, max_features='auto', max_leaf_nodes=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
                     oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [18]:
importancias = floresta.feature_importances_
importancias

array([0.11999261, 0.07458098, 0.06756033, 0.06421159, 0.09090868,
       0.04153654, 0.0482834 , 0.04383134, 0.05014268, 0.02075101,
       0.05347292, 0.0447974 , 0.06458524, 0.03379542, 0.03848595,
       0.036624  , 0.04359915, 0.02568171, 0.02884326, 0.0083158 ])

In [19]:
importancias.shape

(20,)

In [25]:
X_treino2 = X_treino[:,[0,1,2,3]]
X_teste2 = X_teste[:,[0,1,2,3]]

In [26]:
X_treino2

array([[1, 24, 1, 6],
       [0, 36, 3, 4],
       [2, 15, 1, 5],
       ...,
       [0, 9, 3, 4],
       [1, 18, 1, 5],
       [1, 36, 2, 3]], dtype=object)

In [27]:
svm2 = SVC()

In [28]:
svm2.fit(X_treino2, y_treino)

/home/filipanselmo/anaconda3/lib/python3.7/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [30]:
prev2 = svm2.predict(X_teste2)

In [31]:
taxa_acerto2 = accuracy_score(y_teste, prev2)
taxa_acerto2

0.7266666666666667